global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'agency_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['agency-service:8081']
        labels:
          application: 'Agency Service Application'
  - job_name: 'news_category_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['news-and-category-service:8080']
        labels:
          application: 'News and Category Service Application'
  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8082']
        labels:
          application: 'User Service Application'